server.port=8003
# 大模型对话中文乱码UTF8编码处理
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8
spring.application.name=SAA-03ChatModelChatClient
# ================ SpringAIAlibaba Config =====================
spring.ai.dashscope.api-key=sk-ws
spring.ai.dashscope.baseurl=https://ws-nxwi4d6xona0mqsr.cn-beijing.maas.aliyuncs.com/api/v1
spring.ai.dashscope.chat.options.model=qwen-plus
