server.port=8015
# 大模型对话中文乱码UTF8编码处理
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8
spring.application.name=SAA-15LocalMcpClient
# ================ SpringAIAlibaba Config =====================
spring.ai.dashscope.api-key=
spring.ai.dashscope.chat.options.model=qwen-plus
# ================ mcp-client config =====================
spring.ai.mcp.client.type=async
spring.ai.mcp.client.request-timeout=60s
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.sse.connections.mcp-server1.url=http://localhost:8014