server.port=8006
# 大模型对话中文乱码UTF8编码处理
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8
spring.application.name=SAA-06PromptTemplate
# ================ SpringAIAlibaba Config =====================
spring.ai.dashscope.api-key=sk-ws-H.PLXRLPP.iKyy.MEQCIEzc15cSqx7CWeqkcHWqS1bYK5KXT8SrrgqzFt4PIkJMAiBxQimUQ6pkF2DEJ1A2w3owOJlVmUVTmyiGHj2qfNZRJQ
spring.ai.dashscope.baseurl=https://ws-nxwi4d6xona0mqsr.cn-beijing.maas.aliyuncs.com/api/v1
spring.ai.dashscope.chat.options.model=qwen-plus
