server.port=8005
# 大模型对话中文乱码UTF8编码处理
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8
spring.application.name=SAA-05StreamingOutputApplication
# ================ SpringAIAlibaba Config =====================
spring.ai.dashscope.api-key=sk-ws-H.PLELRPL.mzDr.MEUCIAk30j_e4yOTVjPu6WvioRsUrWvpdGZdPyKHltaJfoXoAiEA8tmFhXzMYrsP3ef6k-KKQUiUughV7M45BPjnpQc7msQ
spring.ai.dashscope.baseurl=https://ws-nxwi4d6xona0mqsr.cn-beijing.maas.aliyuncs.com/api/v1
spring.ai.dashscope.chat.options.model=qwen-plus
