server.port=8001
# 大模型对话中文乱码UTF8编码处理
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8
spring.application.name=SAA-02Ollama
# ================ SpringAIAlibaba Config =====================
spring.ai.dashscope.api-key=sk-ws
spring.ai.ollama.baseurl=http://localhost:11434
spring.ai.ollama.model=qwen3:4b

